# Terragon Autonomous SDLC Value Discovery Configuration
# Repository: EchoLoc-NN
# Initialized: 2025-01-01

project:
  name: "EchoLoc-NN"
  type: "python-ml"
  maturity: "nascent"
  domain: "ultrasonic-localization"
  
# Continuous value discovery settings
discovery:
  enabled: true
  schedule: "daily"
  triggers:
    - "git-push"
    - "pr-merge"
    - "tag-creation"
  
# Signal harvesting configuration
signals:
  code_analysis:
    enabled: true
    patterns:
      - "TODO:"
      - "FIXME:"
      - "HACK:"
      - "DEPRECATED:"
      - "XXX:"
      - "BUG:"
      - "OPTIMIZE:"
    git_patterns:
      - "quick fix"
      - "temporary"
      - "workaround"
      - "debt"
  
  static_analysis:
    enabled: true
    tools:
      - "flake8"
      - "mypy"
      - "bandit"
      - "safety"
      - "pip-audit"
    complexity_threshold: 10
    
  dependency_analysis:
    enabled: true
    security_scan: true
    outdated_check: true
    vulnerability_sources:
      - "nvd"
      - "osv"
      - "github-advisory"
  
  performance_analysis:
    enabled: true
    benchmarks:
      - "inference_speed"
      - "training_time"
      - "memory_usage"
      - "model_size"
    thresholds:
      inference_latency_ms: 100
      memory_mb: 512
      model_size_mb: 50

# Value prioritization matrix
prioritization:
  factors:
    business_impact:
      weight: 0.3
      criteria:
        - "user_experience"
        - "performance_improvement"
        - "cost_reduction"
        - "market_differentiation"
    
    technical_debt:
      weight: 0.25
      criteria:
        - "code_complexity"
        - "test_coverage"
        - "documentation_quality"
        - "security_vulnerabilities"
    
    risk_mitigation:
      weight: 0.25
      criteria:
        - "security_risks"
        - "compliance_risks"
        - "operational_risks"
        - "scalability_risks"
    
    innovation_potential:
      weight: 0.2
      criteria:
        - "research_advancement"
        - "technology_adoption"
        - "ecosystem_growth"
        - "community_engagement"

# Autonomous execution settings
execution:
  auto_create_issues: true
  auto_assign_priority: true
  auto_generate_tasks: true
  auto_update_backlog: true
  
  execution_thresholds:
    critical_priority: 0.8
    high_priority: 0.6
    medium_priority: 0.4
    low_priority: 0.2
  
  batch_processing:
    enabled: true
    max_items_per_batch: 10
    batch_interval_hours: 24

# Metrics and tracking
metrics:
  value_delivered:
    - "features_implemented"
    - "bugs_fixed"
    - "performance_improvements"
    - "security_vulnerabilities_resolved"
    - "test_coverage_increase"
    - "documentation_completeness"
  
  development_velocity:
    - "commits_per_week"
    - "prs_merged"
    - "issues_resolved"
    - "code_churn_rate"
  
  quality_indicators:
    - "test_pass_rate"
    - "build_success_rate"
    - "code_coverage"
    - "security_scan_score"
    - "performance_regression_count"

# Integration settings
integrations:
  github:
    enabled: true
    auto_create_issues: true
    label_strategy: "priority-based"
    milestone_management: true
  
  monitoring:
    performance_tracking: true
    error_tracking: true
    user_analytics: false  # Privacy-first approach
  
  notification:
    slack: false
    email: false
    webhook: false

# Domain-specific configurations for ultrasonic localization
domain_specific:
  ml_model_monitoring:
    accuracy_threshold: 0.95
    drift_detection: true
    performance_regression: true
  
  hardware_compatibility:
    supported_platforms:
      - "raspberry-pi"
      - "arduino"
      - "jetson-nano"
    testing_requirements:
      - "hardware-in-loop"
      - "acoustic-chamber"
  
  research_tracking:
    paper_citations: true
    algorithm_improvements: true
    benchmark_comparisons: true

# Value discovery history (maintained by system)
discovery_history: {}

# Last execution metadata (maintained by system)
last_execution:
  timestamp: null
  status: null
  items_discovered: null
  items_executed: null